name: basic_english
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.5
  firebase_core: ^2.27.1
  cloud_functions: ^4.7.1
  firebase_storage: ^11.7.1
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  http: ^1.2.1
  uuid: ^4.4.0
  device_info_plus: ^10.1.0
  gal: ^2.3.0
  image_cropper: ^5.0.1
  image_picker: ^1.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - .env
